server.port: 8081

spring:
  application:
    name: @parent.artifactId@
  profiles:
    active: dev

swagger:
  enabled: true                                       #是否启用swagger，默认：true
  title: 后台管理端                                    #标题
  description: 后台管理端                              #描述
  version: @admin-client.version@                     #版本
  license:                                            #许可证
  licenseUrl:                                         #许可证URL
  termsOfServiceUrl:                                  #服务条款URL
  contact.name: zhangxk                               #维护人
  contact.url:                                        #维护人URL
  contact.email: 980137428@qq.com                     #维护人email
  base-package: com.zxk                               #swagger扫描的基础包，默认：全扫描
  base-path:                                          #需要处理的基础URL规则，默认：/**
  exclude-path:                                       #需要排除的URL规则，默认：空
  host:                                               #文档的host信息，默认：空

#mybatis plus
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zxk.admin.domain.*
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'