server.port: 8081

spring:
  application:
    name: @parent.artifactId@
  redis:
    host: hzajwj.cn
    port: 6379
    password: 123456        # 密码（默认为空）
    timeout: 6000ms         # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10        # 连接池中的最大空闲连接
        min-idle: 5         # 连接池中的最小空闲连接


rocketmq:
  name-server: 123.56.116.9:9876
  producer:
    group: boot_producer_group


#mybatis plus
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zxk.admin.domain.*
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


dubbo:
  scan:
    base-packages: com.zxk.admin.biz.service
  protocol:
    id: dubbo
    name: dubbo
    port: 20001
  registry:
    address: zookeeper://hzajwj.cn:2181
  application:
    name: @artifactId@






