dubbo:
  scan:
    base-packages: com.zxk.admin.biz.service
  protocol:
    id: dubbo
    name: dubbo
    port: 20001
  registry:
    address: zookeeper://hzajwj.cn:2181
  application:
    name: @artifactId@